import { sql } from "drizzle-orm";
import { pgTable, text, varchar, integer, timestamp, boolean, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const users = pgTable("users", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
});

export const insertUserSchema = createInsertSchema(users).pick({
  username: true,
  password: true,
});

export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;

// Papers table
export const papers = pgTable("papers", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  title: text("title").notNull(),
  source: text("source"), // ArXiv, Upload, Online, etc.
  year: varchar("year"),
  authors: text("authors"), // Comma-separated
  abstract: text("abstract"),
  keywords: text("keywords"), // Comma-separated
  filePath: text("file_path"), // Path to uploaded PDF
  sections: jsonb("sections"), // Array of sections
  metadata: jsonb("metadata"), // Additional metadata
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Summaries table - multiple summaries per paper
export const summaries = pgTable("summaries", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  paperId: varchar("paper_id").references(() => papers.id),
  userId: varchar("user_id").notNull().references(() => users.id),
  title: text("title").notNull(),
  content: text("content").notNull(),
  agent: text("agent").notNull(), // Gemini, GPT, Qwen
  style: text("style"), // brief, detailed, teaching
  wordCount: integer("word_count"),
  isEdited: boolean("is_edited").default(false),
  editHistory: jsonb("edit_history"), // Array of edit timestamps
  metadata: jsonb("metadata"), // Generation settings, custom prompt, etc.
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Documents table - unified document library (Notes, Q&A, RAG responses)
export const documents = pgTable("documents", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  type: text("type").notNull(), // summary, qa_set, rag_response, manual
  title: text("title").notNull(),
  content: text("content").notNull(),
  tags: jsonb("tags").default([]), // Array of strings
  wordCount: integer("word_count"),
  questionCount: integer("question_count"), // For Q&A sets
  sourceLinks: jsonb("source_links"), // Array of {type, id, title}
  agent: text("agent"), // If generated by agent
  metadata: jsonb("metadata"), // Type-specific metadata
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Question sets table
export const questionSets = pgTable("question_sets", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  title: text("title").notNull(),
  questions: jsonb("questions").notNull(), // Array of question objects
  sourceDocumentIds: jsonb("source_document_ids"), // Array of paper/note IDs
  agent: text("agent"), // Agent used for generation
  metadata: jsonb("metadata"), // Generation settings
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// RAG queries table
export const ragQueries = pgTable("rag_queries", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  query: text("query").notNull(),
  response: text("response").notNull(),
  agent: text("agent").notNull(), // GPT Web, Gemini Web, Qwen Local
  selectedDocumentIds: jsonb("selected_document_ids"), // Array of IDs
  citations: jsonb("citations"), // Array of citation objects
  settings: jsonb("settings"), // Query settings (maxChunks, temperature, etc.)
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Context templates for RAG
export const contextTemplates = pgTable("context_templates", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  name: text("name").notNull(),
  selectedDocumentIds: jsonb("selected_document_ids").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Export history
export const exports = pgTable("exports", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  documentId: varchar("document_id"), // ID of exported document
  documentType: text("document_type").notNull(), // summary, qa_set, rag_response, document
  format: text("format").notNull(), // pdf, txt, latex, markdown, docx, json, etc.
  filePath: text("file_path"), // Path to exported file
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Type exports
export type Paper = typeof papers.$inferSelect;
export type InsertPaper = typeof papers.$inferInsert;
export type Summary = typeof summaries.$inferSelect;
export type InsertSummary = typeof summaries.$inferInsert;
export type Document = typeof documents.$inferSelect;
export type InsertDocument = typeof documents.$inferInsert;
export type QuestionSet = typeof questionSets.$inferSelect;
export type InsertQuestionSet = typeof questionSets.$inferInsert;
export type RagQuery = typeof ragQueries.$inferSelect;
export type InsertRagQuery = typeof ragQueries.$inferInsert;
export type ContextTemplate = typeof contextTemplates.$inferSelect;
export type InsertContextTemplate = typeof contextTemplates.$inferInsert;
export type Export = typeof exports.$inferSelect;
export type InsertExport = typeof exports.$inferInsert;
